apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  selector:
    run: gop-file-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31200